### PR TITLE
mongoose connection options added

### PR DESCRIPTION
**Pull request by gidkom**

### CODE REVIEW

**Comment by sharvit** [comment]
Thanks you for the contribution @gidkom :+1: 

Can you please provide some info about this change?
How the behavior changed? Why is it necessary?

Thanks

**Comment by gidkom** [comment]
The change is to prevent deprecation warning message  in mongoose >= 4.11.0 where it is required to have `useMongoClient` property set in options for the mongodb connection

**Comment by sharvit** [comment]
Thank you @gidkom 👍 
I will soon release it in a new version, together with some other changes.

**Comment by sharvit** [comment]
Released as a patch [v1.0.5](https://github.com/sharvit/mongoose-data-seed/releases/tag/v1.0.5)

Thanks @gidkom @abdulbasitkay

**Pull request merged**
